GCN fixes
- Fix for graphs with isolated nodes:

    dgl._ffi.base.DGLError: There are 0-in-degree nodes in the graph, output
    for those nodes will be invalid. This is harmful for some applications,
    causing silent performance regression. Adding self-loop on the input
    graph by calling ±g = dgl.add_self_loop(g)± will resolve the issue.
    Setting ±±allow_zero_in_degree±± to be ±True± when constructing this
    module will suppress the check and let the code run.

- Added add_self_loop parameter to embedding constructor to overcome this problem.
- Added more GCN tests (for all datasets)